import Head from "next/head"
import { Layout } from "./components/layout/layout"


export default function ContactMe() {
  return (
    <>
      <Head>
        <title>Tong Bekas | Klient</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div className='px-4'>
            <div className='mt-16'>
              <h1 className='text-5xl text-center font-semibold text-gray-800 '>KLIEN KAMI</h1>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}