import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Layout } from "./components/layout/layout";
import kolase from "./../../public/img/kolase.png";
import { Button } from "@material-tailwind/react";
import murah from "./../../public/img/murah.jpg"
import quality from "./../../public/img/quality.jpg"
import cepat from "./../../public/img/cepat.jpg"
import { CardProduct } from "./components/card/card";
import { EnumCard } from "@/utils/Card/EnumCardDummy";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const dummyCard = EnumCard()
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Tong Bekas | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div className="px-10">
            {/* <div className="mt-16">
              <h1 className="text-5xl text-center font-semibold title text-gray-800 ">
                SELAMAT DATANG DI CV UTAMA
              </h1>
            </div> */}
            <div className="grid grid-cols-2 gap-6">
              <div className="flex justify-center flex-col">
                <h2 className="font-semibold text-sm text-gray-800">BUTUH JERIGEN ATAU TONG ? </h2>
                <h1 className="font-bold text-6xl">CV UTAMA</h1>
                <h6 className="font-medium mt-6">Menyediakan bebrbagai jenis tong</h6>
                <p className="mt-3"> Lorem ipsum dolor sit amet consectetur adipisicing elit. Error
                  nam eveniet consequuntur, asperiores placeat non aut? Amet
                  itaque iusto beatae.Lorem ipsum dolor sit amet consectetur adipisicing elit. Error
                  nam eveniet consequuntur, asperiores placeat non aut? Amet
                  itaque iusto beatae.
                </p>
              </div>
              <div className="flex justify-center">
                <img src="/img/ide.jpg" className="w-3/4" />
              </div>
            </div>
            <div className="mt-36 text-center">
              <h3 className="text-5xl text-center font-semibold title text-gray-800">Distributor Drum</h3>
            </div>
            <div className="flex gap-6 mt-14">
              <Image src={kolase} alt="kolase" className="rounded-xl w-2/4 brightness-50 hue-rotate-30" />
              <div className="flex flex-col justify-center gap-6">
                <h3 className="text-gray-800 text-2xl font-medium sub-title">
                  Menyediakan berbagai jenis tong dan juga jerigen
                </h3>
                <div className="mt-10">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Error
                  nam eveniet consequuntur, asperiores placeat non aut? Amet
                  itaque iusto beatae.Lorem ipsum dolor sit amet consectetur
                  adipisicing elit. Error nam eveniet consequuntur, asperiores
                  placeat non aut? Amet itaque iusto beatae.Lorem ipsum dolor
                  sit amet consectetur adipisicing elit. Error nam eveniet
                  consequuntur, asperiores placeat non aut? Amet itaque iusto
                  beatae.
                </div>
                <div className="mt-10">
                  <Button variant="filled" onClick={() => router.push("/produk") }  color="deep-purple" className="flex items-center gap-2">
                    Lihat Product
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth={2}
                      stroke="currentColor"
                      className="h-5 w-5"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M17.25 8.25L21 12m0 0l-3.75 3.75M21 12H3"
                      />
                    </svg>
                  </Button>
                </div>
              </div>
            </div>
            {/* content kedua */}
            <div className="mt-24">
              <h3 className="text-5xl text-center font-semibold title text-gray-800">Kenapa harus beli disini </h3>
              <div className="flex gap-8 w-full mt-10 ">
                <div className="w-1/3">
                  <Image src={quality} alt="quality" />
                  <p className="text-center text-lg sub-title font-medium">Kualitas Terjamin</p>
                </div>
                <div className="w-1/3">
                  <Image src={murah} alt="murah" />
                  <p className="text-center text-lg sub-title font-medium">Harga Terjangkau</p>
                </div>
                <div className="w-1/3">
                  <Image src={cepat} alt="cepat" />
                  <p className="text-center text-lg sub-title font-medium">Pengiriman Cepat</p>
                </div>
              </div>
            </div>

            {/* content ketiga */}
            <div className="mt-24">
              <h3 className="text-5xl text-center font-semibold title text-gray-800">Produk Kami</h3>
              <div className="mt-16 grid grid-cols-3 gap-4">
                {dummyCard.map((item, index) => (
                  <div className="w-full flex justify-center" key={index}>
                    <CardProduct
                      title = {item.title}
                      deskripsi = {item.deskripsi}
                      img = {`img/${item.img}`}
                    />
                  </div>
                ))}
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
