import Head from "next/head"
import { Layout } from "../components/layout/layout"
import { EnumProduct } from "@/utils/Product/EnumProductDummy"
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Image from "next/image";


export default function ContactMe() {

  const listProduct = EnumProduct();
  const router = useRouter()
  const [data, setData] = useState()
  
  useEffect(() => {
    listProduct.forEach(item => {
      if(item.slug === router.query.detailProduct ) {
        setData(item)
      }
    })
  }, [])

  return (
    <>
      <Head>
        <title>Tong Bekas | Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div className='px-4'>
            <div className='mt-16'>
              <h1 className='text-5xl text-center font-semibold text-gray-800 '>DETAIL PRODUK</h1>
              <div className="px-80 mt-24">
                {data ? 
                  <div className="flex flex-col justify-center items-center">
                    <img src={`/img/${data.img}`} alt="detail" className="rounded-2xl w-3/4" /> 
                    <h3 className="text-center text-2xl font-semibold my-14">{data.title}</h3>
                    <div className="text-justify ">{data.detail}</div>
                  </div>
                  : null}
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}