import Head from "next/head"
import { Layout } from "@/components/layout/layout"
import { EnumProduct } from "@/utils/Product/EnumProductDummy"
import { CardProduct } from "@/components/card/card"
import { useRouter } from "next/router"
import { list } from "postcss"


export default function Product() {
  const enumProduct = EnumProduct()
  const router = useRouter()

  const OnCLickProduct = (props) => {
    const listProduct = EnumProduct()
    listProduct.forEach(item => {
      if(item.slug === props) {
        router.push(`/produk/${props}`)
      }
    })
  }
  return (
    <>
      <Head>
        <title>Tong Bekas | Produk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div className='px-4'>
            <div className='mt-16'>
              <h1 className='md:text-5xl text-2xl text-center font-semibold text-gray-800 '>PRODUCT KAMI</h1>
              <div className="mt-24 grid lg:grid-cols-3 md:grid-cols-2 grid-cols-1 gap-4">
                {enumProduct.map((item, index) => (
                  <div key={index} className="flex justify-center">
                    <CardProduct
                      title = {item.title}
                      img = {`img/${item.img}`}
                      deskripsi = {item.deskripsi}
                      onClick = {() => OnCLickProduct(item.slug)}
                    />
                  </div>
                ))}
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}